In [36]:
text = """A black hole is a region of spacetime where gravity is so strong that nothing—no particles or even electromagnetic radiation such as light—can escape from it.
This cosmic entity forms when a massive star collapses under its own gravity at the end of its life cycle.
The boundary of no escape is called the event horizon.
Although it has a great effect on the fate and trajectory of light that passes close to it, the event horizon itself emits no radiation.
Because it reflects no light, it is incredibly difficult to observe directly"""

In [37]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [38]:
token = Tokenizer()
token.fit_on_texts([text])

In [39]:
len(token.word_index)

65

In [40]:
from re import S
for sentence in text.split('\n'):
  print(sentence)

A black hole is a region of spacetime where gravity is so strong that nothing—no particles or even electromagnetic radiation such as light—can escape from it.
This cosmic entity forms when a massive star collapses under its own gravity at the end of its life cycle.
The boundary of no escape is called the event horizon.
Although it has a great effect on the fate and trajectory of light that passes close to it, the event horizon itself emits no radiation.
Because it reflects no light, it is incredibly difficult to observe directly


In [41]:
from re import S
for sentence in text.split('\n'):
  print(token.texts_to_sequences([sentence]))

[[3, 16, 17, 4, 3, 18, 5, 19, 20, 7, 4, 21, 22, 8, 23, 24, 25, 26, 27, 9, 28, 29, 30, 10, 31, 1]]
[[32, 33, 34, 35, 36, 3, 37, 38, 39, 40, 11, 41, 7, 42, 2, 43, 5, 11, 44, 45]]
[[2, 46, 5, 6, 10, 4, 47, 2, 12, 13]]
[[48, 1, 49, 3, 50, 51, 52, 2, 53, 54, 55, 5, 14, 8, 56, 57, 15, 1, 2, 12, 13, 58, 59, 6, 9]]
[[60, 1, 61, 6, 14, 1, 4, 62, 63, 15, 64, 65]]


In [42]:
input_list = []
for sentence in text.split('\n'):
  token_sentence = token.texts_to_sequences([sentence])[0]

  for i in range(1,len(token_sentence)):
    input_list.append(token_sentence[:i+1])

In [43]:
input_list

[[3, 16],
 [3, 16, 17],
 [3, 16, 17, 4],
 [3, 16, 17, 4, 3],
 [3, 16, 17, 4, 3, 18],
 [3, 16, 17, 4, 3, 18, 5],
 [3, 16, 17, 4, 3, 18, 5, 19],
 [3, 16, 17, 4, 3, 18, 5, 19, 20],
 [3, 16, 17, 4, 3, 18, 5, 19, 20, 7],
 [3, 16, 17, 4, 3, 18, 5, 19, 20, 7, 4],
 [3, 16, 17, 4, 3, 18, 5, 19, 20, 7, 4, 21],
 [3, 16, 17, 4, 3, 18, 5, 19, 20, 7, 4, 21, 22],
 [3, 16, 17, 4, 3, 18, 5, 19, 20, 7, 4, 21, 22, 8],
 [3, 16, 17, 4, 3, 18, 5, 19, 20, 7, 4, 21, 22, 8, 23],
 [3, 16, 17, 4, 3, 18, 5, 19, 20, 7, 4, 21, 22, 8, 23, 24],
 [3, 16, 17, 4, 3, 18, 5, 19, 20, 7, 4, 21, 22, 8, 23, 24, 25],
 [3, 16, 17, 4, 3, 18, 5, 19, 20, 7, 4, 21, 22, 8, 23, 24, 25, 26],
 [3, 16, 17, 4, 3, 18, 5, 19, 20, 7, 4, 21, 22, 8, 23, 24, 25, 26, 27],
 [3, 16, 17, 4, 3, 18, 5, 19, 20, 7, 4, 21, 22, 8, 23, 24, 25, 26, 27, 9],
 [3, 16, 17, 4, 3, 18, 5, 19, 20, 7, 4, 21, 22, 8, 23, 24, 25, 26, 27, 9, 28],
 [3,
  16,
  17,
  4,
  3,
  18,
  5,
  19,
  20,
  7,
  4,
  21,
  22,
  8,
  23,
  24,
  25,
  26,
  27,
  9,
  28,
  29]

In [44]:
max_len = max([len(x) for x in input_list])
max_len

26

In [45]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
pad_sequences(input_list,maxlen=max_len,padding='pre')

array([[ 0,  0,  0, ...,  0,  3, 16],
       [ 0,  0,  0, ...,  3, 16, 17],
       [ 0,  0,  0, ..., 16, 17,  4],
       ...,
       [ 0,  0,  0, ..., 62, 63, 15],
       [ 0,  0,  0, ..., 63, 15, 64],
       [ 0,  0,  0, ..., 15, 64, 65]], dtype=int32)

In [46]:
padded_input = pad_sequences(input_list,maxlen=max_len,padding='pre')

In [47]:
x = padded_input[:,:-1]
y = padded_input[:,-1]
print(x)
print(y)

[[ 0  0  0 ...  0  0  3]
 [ 0  0  0 ...  0  3 16]
 [ 0  0  0 ...  3 16 17]
 ...
 [ 0  0  0 ...  4 62 63]
 [ 0  0  0 ... 62 63 15]
 [ 0  0  0 ... 63 15 64]]
[16 17  4  3 18  5 19 20  7  4 21 22  8 23 24 25 26 27  9 28 29 30 10 31
  1 33 34 35 36  3 37 38 39 40 11 41  7 42  2 43  5 11 44 45 46  5  6 10
  4 47  2 12 13  1 49  3 50 51 52  2 53 54 55  5 14  8 56 57 15  1  2 12
 13 58 59  6  9  1 61  6 14  1  4 62 63 15 64 65]


In [48]:
token.word_index

{'it': 1,
 'the': 2,
 'a': 3,
 'is': 4,
 'of': 5,
 'no': 6,
 'gravity': 7,
 'that': 8,
 'radiation': 9,
 'escape': 10,
 'its': 11,
 'event': 12,
 'horizon': 13,
 'light': 14,
 'to': 15,
 'black': 16,
 'hole': 17,
 'region': 18,
 'spacetime': 19,
 'where': 20,
 'so': 21,
 'strong': 22,
 'nothing—no': 23,
 'particles': 24,
 'or': 25,
 'even': 26,
 'electromagnetic': 27,
 'such': 28,
 'as': 29,
 'light—can': 30,
 'from': 31,
 'this': 32,
 'cosmic': 33,
 'entity': 34,
 'forms': 35,
 'when': 36,
 'massive': 37,
 'star': 38,
 'collapses': 39,
 'under': 40,
 'own': 41,
 'at': 42,
 'end': 43,
 'life': 44,
 'cycle': 45,
 'boundary': 46,
 'called': 47,
 'although': 48,
 'has': 49,
 'great': 50,
 'effect': 51,
 'on': 52,
 'fate': 53,
 'and': 54,
 'trajectory': 55,
 'passes': 56,
 'close': 57,
 'itself': 58,
 'emits': 59,
 'because': 60,
 'reflects': 61,
 'incredibly': 62,
 'difficult': 63,
 'observe': 64,
 'directly': 65}

In [49]:
from tensorflow.keras.utils import to_categorical
to_categorical(y,num_classes=66)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [50]:
y.shape

(88,)

In [51]:
x.shape

(88, 25)

In [52]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Embedding

In [53]:
model = Sequential()
model.add(Embedding(88,100,input_length=33))
model.add(LSTM(150))
model.add(Dense(88,activation='softmax'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [54]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [55]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [56]:
x.shape

(88, 25)

In [57]:
y.shape

(88,)

In [58]:
model.fit(x,y,epochs=100)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 6s 93ms/step - accuracy: 0.0000e+00 - loss: 4.4768
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - accuracy: 0.1058 - loss: 4.4586
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.1197 - loss: 4.4308
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 73ms/step - accuracy: 0.0692 - loss: 4.3544
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.0518 - loss: 4.2241
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.0558 - loss: 4.1362
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.0806 - loss: 4.0629
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.1037 - loss: 4.0628
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.0998 - loss: 3.9592
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.1019 - loss: 3.9105
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.1019 - loss: 3.8395
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.086

In [59]:
text_1 = "black hole"

token_text_1 =token.texts_to_sequences([text_1])[0]


In [60]:
padded_text = pad_sequences([token_text_1],maxlen=33,padding='pre')

In [61]:
model.predict(padded_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 210ms/step


array([[3.62754799e-05, 4.18753363e-02, 7.00509350e-04, 2.99532302e-02,
        2.43370965e-01, 8.50404575e-02, 8.40631351e-02, 5.90744603e-04,
        1.96219757e-04, 4.50796331e-04, 2.88774818e-02, 1.88739505e-04,
        3.55716620e-04, 4.87736310e-04, 1.38234459e-02, 1.01858552e-03,
        5.78705221e-02, 1.93568349e-01, 7.34767737e-03, 2.34981743e-03,
        2.74350343e-04, 2.44610710e-04, 2.83559551e-04, 1.56621332e-04,
        2.80492502e-04, 1.64002777e-04, 2.29043217e-04, 2.52093188e-04,
        1.91307452e-04, 6.20085048e-04, 7.79685506e-04, 1.23120041e-03,
        5.15197644e-05, 1.01750158e-02, 2.48891078e-02, 1.84336379e-02,
        1.00411018e-02, 5.23810880e-03, 1.12027582e-03, 7.57148140e-04,
        3.07829032e-04, 2.05919234e-04, 4.51770939e-05, 2.22213293e-05,
        6.74027033e-05, 5.02885996e-05, 2.70791333e-02, 4.63560270e-03,
        3.00492047e-05, 2.56039035e-02, 8.46191682e-03, 2.10482464e-03,
        1.19836908e-03, 2.54859071e-04, 1.79411887e-04, 6.552052

In [62]:
import numpy as np
pos = np.argmax(model.predict(padded_text))
pos

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step


np.int64(4)

In [63]:
for word, index in token.word_index.items():
  if index == pos:
    print(word)

is


In [64]:
text_2 = "A black hole is a region of"

token_text_2 =token.texts_to_sequences([text_2])[0]
padded_text_1 = pad_sequences([token_text_2],maxlen=33,padding='pre')
model.predict(padded_text_1)
pos_1 = np.argmax(model.predict(padded_text_1))

for word, index in token.word_index.items():
  if index == pos_1:
    print(word)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
spacetime
